#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/guava.jar:$APPDIR/lib/p1LakshmiSampathSomanathPagolu.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-aarch64.jar:$APPDIR/lib/gluegen-rt-natives-linux-aarch64.jar:$APPDIR/lib/guava.jar:$APPDIR/lib/cmudict04.jar:$APPDIR/lib/cmulex.jar:$APPDIR/lib/cmutimelex.jar:$APPDIR/lib/cmu_time_awb.jar:$APPDIR/lib/cmu_us_kal.jar:$APPDIR/lib/en_us.jar:$APPDIR/lib/freetts.jar:$APPDIR/lib/mbrola.jar:$APPDIR/lib/ttslib.jar:$APPDIR/lib/controlP5.jar" p1LakshmiSampathSomanathPagolu "$@"
